# Generated by Django 3.2.25 on 2024-11-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ImageField(upload_to='static/images/', verbose_name='Content image')),
                ('style_input', models.CharField(choices=[('my style', 'my style'), ('preloaded style', 'preloaded style')], default='preloaded style', max_length=100, verbose_name='Style input')),
                ('style', models.ImageField(blank=True, upload_to='static/images/', verbose_name='Style image')),
                ('strength', models.CharField(choices=[('0.2', 'low'), ('0.5', 'medium'), ('0.8', 'high')], default='0.8', max_length=100, verbose_name='Style effect')),
                ('preloaded_styles', models.CharField(choices=[('anonymous_fuxi', 'anonymous_fuxi'), ('askim_andersson', 'askim_andersson'), ('bcbey_han', 'bcbey_han'), ('darkspirit_ninakossman', 'darkspirit_ninakossman'), ('laluna_bajo', 'laluna_bajo'), ('lights_in_india', 'lights_in_india'), ('monsternavajo_sandd', 'monsternavajo_sandd'), ('pastorale_jansen', 'pastorale_jansen'), ('tegelveld_springendedieren', 'tegelveld_springendedieren'), ('tingatinga_daudi', 'tingatinga_daudi')], default='tingatinga_daudi', max_length=100, verbose_name='Preloaded styles')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Style_image', models.ImageField(upload_to='static/images/', verbose_name='Style_image')),
                ('Choose_style', models.CharField(choices=[('anonymous_fuxi', 'anonymous_fuxi'), ('askim_andersson', 'askim_andersson'), ('bcbey_han', 'bcbey_han'), ('darkspirit_ninakossman', 'darkspirit_ninakossman'), ('laluna_bajo', 'laluna_bajo'), ('lights_in_india', 'lights_in_india'), ('monsternavajo_sandd', 'monsternavajo_sandd'), ('pastorale_jansen', 'pastorale_jansen'), ('tegelveld_springendedieren', 'tegelveld_springendedieren'), ('tingatinga_daudi', 'tingatinga_daudi')], default='0.5', max_length=100)),
            ],
        ),
    ]
