# Generated by Django 3.2.25 on 2024-11-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20241121_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stylemodel',
            name='content',
            field=models.ImageField(upload_to='media/images/%Y/%m/%d', verbose_name='Content image'),
        ),
        migrations.AlterField(
            model_name='stylemodel',
            name='mixed',
            field=models.ImageField(blank=True, upload_to='media/output/%Y/%m/%d', verbose_name='Mixed image'),
        ),
        migrations.AlterField(
            model_name='stylemodel',
            name='style',
            field=models.ImageField(blank=True, upload_to='media/images/%Y/%m/%d', verbose_name='Style image'),
        ),
    ]
